export const ROUTES = {
  home: '/',
  summary: '/summary',
  user: '/user/:username',
  coin: '/coin/:coinName',
  userPath: '/user/',
  addTrans: '/addtransaction',
  fundTransfer: '/fundtransfer',
  adminMenu: '/adminmenu',
  adminLogin: '/adminlogin',
  transactions: '/transactions',
  addUser: '/addUser',
  addCoin: '/addcoin',
  loginUser: '/loginuser',
  tradingMenu: '/trading',
  tradingMenuMobile: '/tradingmobile',
  automations: '/automation',
  stopLossBot: '/stoplossbot',
  leaderboard: '/leaderboard',
};
