export const ROUTES = {
  home: '/',
  summary: '/summary',
  user: '/user/:username',
  userPath: '/user/',
  addTrans: '/addtransaction',
  fundTransfer: '/fundtransfer',
  adminMenu: '/adminmenu',
  adminLogin: '/adminlogin',
  transactions: '/transactions',
  addUser: '/addUser',
  loginUser: '/loginuser',
  tradingMenu: '/trading',
  tradingMenuMobile: '/tradingmobile',
};
